openapi: 3.0.1
info:
  description: Dybov's and Lavrov's blse lab
  title: Rubbable api
  version: 1.0.0
servers:
- url: http://localhost:8000/api
paths:
  /users/me/:
    get:
      description: Get self user profile info
      parameters:
      - in: header
        name: user-id
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
          description: Ok
      x-accepts: application/json
  /teams/:
    get:
      description: Get teams list
      parameters:
      - in: header
        name: user-id
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/TeamDto'
                type: array
          description: user found
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Validation Error
      x-accepts: application/json
  /teams/{id}/:
    get:
      description: Get team by id
      parameters:
      - in: header
        name: user-id
        required: true
        schema:
          type: integer
      - in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/TeamDto'
                type: array
          description: user found
      x-accepts: application/json
  /tournaments/:
    get:
      description: get all Tournaments
      parameters:
      - in: header
        name: user-id
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ListTournamentDto'
                type: array
          description: List of tournaments
      x-accepts: application/json
    post:
      description: Create new tournament
      parameters:
      - in: header
        name: user-id
        required: true
        schema:
          type: integer
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/CreateTournamentDto'
        required: false
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveTournamentDto'
          description: Created
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Validation Error
      x-codegen-request-body-name: body
      x-contentType: '*/*'
      x-accepts: application/json
  /games/{game-id}/approve/:
    post:
      description: Approve game
      parameters:
      - in: header
        name: user-id
        required: true
        schema:
          type: integer
      - in: path
        name: game-id
        required: true
        schema:
          type: integer
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameDto'
          description: Created
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Validation Error
      x-accepts: application/json
  /games/{game-id}/disapprove/:
    post:
      description: Disapprove game
      parameters:
      - in: header
        name: user-id
        required: true
        schema:
          type: integer
      - in: path
        name: game-id
        required: true
        schema:
          type: integer
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameDto'
          description: Created
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Validation Error
      x-accepts: application/json
  /matches/{match-id}/play-game/:
    post:
      description: Add game to match
      parameters:
      - in: header
        name: user-id
        required: true
        schema:
          type: integer
      - in: path
        name: match-id
        required: true
        schema:
          type: integer
      - in: query
        name: winnerId
        required: true
        schema:
          type: integer
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchDto'
          description: Created
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Validation Error
      x-accepts: application/json
  /matches/{match-id}/drop/:
    post:
      description: Drop match games
      parameters:
      - in: header
        name: user-id
        required: true
        schema:
          type: integer
      - in: path
        name: match-id
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchDto'
          description: Ok
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Validation Error
      x-accepts: application/json
components:
  schemas:
    UserDto:
      example:
        id: 0
        username: username
      properties:
        id:
          type: integer
        username:
          type: string
      type: object
    TeamDto:
      example:
        name: name
        id: 0
      properties:
        id:
          type: integer
        name:
          type: string
      type: object
    ListTournamentDto:
      example:
        maxGames: 1
        maxJudges: maxJudges
        name: name
        approvalRatio: 6.027456183070403
        id: 0
        startDate: startDate
      properties:
        id:
          type: integer
        name:
          type: string
        startDate:
          type: string
        maxJudges:
          type: string
        approvalRatio:
          type: number
        maxGames:
          type: integer
      type: object
    GameVoteDto:
      example:
        id: 2
        isApproved: true
        judgeId: 4
      properties:
        id:
          type: integer
        judgeId:
          type: integer
        isApproved:
          type: boolean
      type: object
    GameDto:
      example:
        winnerId: 3
        id: 9
        gameVotes:
        - id: 2
          isApproved: true
          judgeId: 4
        - id: 2
          isApproved: true
          judgeId: 4
      properties:
        id:
          type: integer
        winnerId:
          type: integer
        gameVotes:
          items:
            $ref: '#/components/schemas/GameVoteDto'
          type: array
      type: object
    MatchDto:
      example:
        team2Id: 2
        games:
        - winnerId: 3
          id: 9
          gameVotes:
          - id: 2
            isApproved: true
            judgeId: 4
          - id: 2
            isApproved: true
            judgeId: 4
        - winnerId: 3
          id: 9
          gameVotes:
          - id: 2
            isApproved: true
            judgeId: 4
          - id: 2
            isApproved: true
            judgeId: 4
        team1Id: 5
        id: 5
        nextMatchId: 7
      properties:
        id:
          type: integer
        team1Id:
          type: integer
        team2Id:
          type: integer
        nextMatchId:
          type: integer
        games:
          items:
            $ref: '#/components/schemas/GameDto'
          type: array
      type: object
    RetrieveTournamentDto:
      example:
        teams:
        - name: name
          id: 0
        - name: name
          id: 0
        maxGames: 1
        maxJudges: maxJudges
        name: name
        approvalRatio: 6.027456183070403
        id: 0
        judges:
        - id: 0
          username: username
        - id: 0
          username: username
        matches:
        - team2Id: 2
          games:
          - winnerId: 3
            id: 9
            gameVotes:
            - id: 2
              isApproved: true
              judgeId: 4
            - id: 2
              isApproved: true
              judgeId: 4
          - winnerId: 3
            id: 9
            gameVotes:
            - id: 2
              isApproved: true
              judgeId: 4
            - id: 2
              isApproved: true
              judgeId: 4
          team1Id: 5
          id: 5
          nextMatchId: 7
        - team2Id: 2
          games:
          - winnerId: 3
            id: 9
            gameVotes:
            - id: 2
              isApproved: true
              judgeId: 4
            - id: 2
              isApproved: true
              judgeId: 4
          - winnerId: 3
            id: 9
            gameVotes:
            - id: 2
              isApproved: true
              judgeId: 4
            - id: 2
              isApproved: true
              judgeId: 4
          team1Id: 5
          id: 5
          nextMatchId: 7
        startDate: startDate
      properties:
        id:
          type: integer
        name:
          type: string
        startDate:
          type: string
        maxJudges:
          type: string
        approvalRatio:
          type: number
        maxGames:
          type: integer
        judges:
          items:
            $ref: '#/components/schemas/UserDto'
          type: array
        teams:
          items:
            $ref: '#/components/schemas/TeamDto'
          type: array
        matches:
          items:
            $ref: '#/components/schemas/MatchDto'
          type: array
      type: object
    CreateTournamentDto:
      example:
        maxGames: 1
        maxJudges: maxJudges
        name: name
        approvalRatio: 6.027456183070403
        judgesIds:
        - 5
        - 5
        id: 0
        teamsIds:
        - 5
        - 5
        startDate: startDate
      properties:
        id:
          type: integer
        name:
          type: string
        startDate:
          type: string
        maxJudges:
          type: string
        approvalRatio:
          type: number
        maxGames:
          type: integer
        judgesIds:
          items:
            type: integer
          type: array
        teamsIds:
          items:
            type: integer
          type: array
      type: object
x-original-swagger-version: "2.0"

